# -*- coding: utf-8 -*-
"""FinnMMEval_Task3_Qwen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3C-fnYY06Nbrds0YPVy9M9qrvrWwcn0
"""

!pip install -U bitsandbytes accelerate transformers

!pip install transformers torch pandas datasets

import pandas as pd
import numpy as np
import torch
from transformers import pipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from datasets import load_dataset
import re

# 1. Initialize the FinBERT Pipeline
# Setting device=0 ensures it utilizes the free T4 GPU in Colab instead of the CPU
print("Loading FinBERT model...")
device = 0 if torch.cuda.is_available() else -1
finbert = pipeline(
    "text-classification",
    model="ProsusAI/finbert",
    device=device
)

# ======================================================================= #
# The following function gets the sentiment analysis for just initial 512
# tokens due to the limitation of the FinBERT
# ======================================================================= #

# def get_sentiment_score(news_data):
#     """
#     Takes news data (handles both lists and strings), runs it through FinBERT,
#     and returns a numerical score.
#     """
#     # Fix: If the dataset stores daily news as a list of articles, join them into one string
#     if isinstance(news_data, (list, tuple)):
#         # Join non-empty items with a space
#         news_text = " ".join([str(item) for item in news_data if item])
#     else:
#         news_text = str(news_data)

#     # Handle truly empty or missing text
#     if not news_text or len(news_text.strip()) == 0 or news_text.strip().lower() in ['nan', 'none']:
#         return 0.0

#     try:
#         # Pass to FinBERT (truncation handles texts longer than 512 tokens)
#         result = finbert(news_text, padding=True, truncation=True, max_length=512)[0]
#         label = result['label']

#         if label == 'positive':
#             return 1.0
#         elif label == 'negative':
#             return -1.0
#         else:
#             return 0.0

#     except Exception as e:
#         print(f"Error processing text: {e}")
#         return 0.0

# ========================================================================= #
# The following functions performs fixed length chunking for 350 words and
# then cummulates the score for sentiment score of the news
# ========================================================================= #

def get_chunked_sentiment(news_data):
    """
    Splits long news text into chunks, scores each chunk with FinBERT,
    and intelligently aggregates the score.
    """
    # 1. Clean and prepare the text
    if isinstance(news_data, (list, tuple)):
        news_text = " ".join([str(item) for item in news_data if item])
    else:
        news_text = str(news_data)

    if not news_text or len(news_text.strip()) == 0 or news_text.strip().lower() in ['nan', 'none']:
        return 0.0

    # 2. Split into chunks of roughly 350 words
    # (350 words is a safe buffer to ensure we stay under the 512 subword token limit)
    words = news_text.split()
    chunk_size = 350
    chunks = [" ".join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]

    chunk_scores = []

    # 3. Score each chunk
    for chunk in chunks:
        try:
            # We still use truncation=True just as a fail-safe
            result = finbert(chunk, padding=True, truncation=True, max_length=512)[0]
            label = result['label']

            if label == 'positive':
                chunk_scores.append(1.0)
            elif label == 'negative':
                chunk_scores.append(-1.0)
            else:
                chunk_scores.append(0.0)
        except Exception as e:
            print(f"Error on chunk: {e}")
            continue

    # 4. Smart Aggregation
    if not chunk_scores:
        return 0.0

    # Option A: Simple Average
    # return sum(chunk_scores) / len(chunk_scores)

    # Option B (Recommended): "Extreme" Average
    # Filter out the 0s so boring paragraphs don't dilute the important news
    active_scores = [score for score in chunk_scores if score != 0.0]

    if not active_scores:
        return 0.0 # The whole article was truly neutral

    # Return the average of the opinionated chunks
    return sum(active_scores) / len(active_scores)

# 3. Load the BTC split specifically
print("Loading BTC dataset...")
dataset_btc = load_dataset("TheFinAI/CLEF_Task3_Trading", split="BTC")
df_btc = dataset_btc.to_pandas()

# 4. Apply the Scoring Function
print("Calculating sentiment scores... ")
# df_sample = df_btc.head(20).copy()
# df_btc['news_sentiment'] = df_btc['news'].apply(get_sentiment_score)
df_btc['news_sentiment'] = df_btc['news'].apply(get_chunked_sentiment)

# short-term trend (5-day percentage change)
df_btc['trend_5d'] = df_btc['prices'].pct_change(5).fillna(0)

# smooth out the noisy news with a 3-day rolling sentiment
df_btc['sentiment_3d_avg'] = df_btc['news_sentiment'].rolling(window=3).mean().fillna(0)

# View the results
print("\n--- BTC Sentiment Results ---")
print(df_btc[['date', 'news_sentiment']].head(10))

# 5. Load the TSLA split specifically
print("Loading TSLA dataset...")
dataset_tsla = load_dataset("TheFinAI/CLEF_Task3_Trading", split="TSLA")
df_tsla = dataset_tsla.to_pandas()

# 6. Apply the Scoring Function
print("Calculating sentiment scores... ")
# df_sample = df_btc.head(20).copy()
# df_tsla['news_sentiment'] = df_tsla['news'].apply(get_sentiment_score)
df_tsla['news_sentiment'] = df_tsla['news'].apply(get_chunked_sentiment)

# short-term trend (5-day percentage change)
df_tsla['trend_5d'] = df_tsla['prices'].pct_change(5).fillna(0)

# Smooth out the noisy news with a 3-day rolling sentiment
df_tsla['sentiment_3d_avg'] = df_tsla['news_sentiment'].rolling(window=3).mean().fillna(0)

# View the results
print("\n--- TSLA Sentiment Results ---")
print(df_tsla[['date', 'news_sentiment']].head(10))

"""Running The Model"""

# 1. Quantization Setup (The "Magic" for Colab T4)
print("Configuring 4-bit quantization...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

# 2. Load the LLM and Tokenizer
model_id = "Qwen/Qwen2.5-7B-Instruct"
print(f"Loading {model_id}...")

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto" # Automatically maps to your T4 GPU
)

# 3. Define the Zero-Shot Prompt & Inference Function
def get_decision_and_reasoning(row):
    """
    Constructs the prompt Prompt_i = N_i + P_i + Q_i and extracts decision/reasoning.
    """
    # N_i: News and Sentiment (assuming you ran the previous FinBERT step)
    # If news_sentiment isn't calculated yet, default to 0 for this demo
    sentiment = row.get('news_sentiment', 0.0)
    trend_5d = row['trend_5d']
    # P_i: Price and Momentum
    price = row['prices']
    momentum = row['momentum']

    # Q_i: The Query
    prompt = f"""You are a quantitative financial agent. Analyze the following data for an asset:
- Current Price: {price}
- Momentum: {momentum}
- Daily News Sentiment Score: {sentiment} (Scale: -1 highly negative to 1 highly positive)

Based on this, make a trading decision for tomorrow.
Provide your response strictly in the following format:
Decision: [BUY, SELL, or HOLD]
Reasoning: [One brief sentence explaining why]
"""

    prompt_b = f"""You are a risk-averse quantitative cryptocurrency trader specializing in Bitcoin.
Your goal is to maximize the Sharpe Ratio by preserving capital and only taking high-probability trades.

Today's Data:
- Current Price: {price}
- Momentum: {momentum}
- Daily News Sentiment Score: {sentiment} (Scale: -1 highly negative to 1 highly positive)

Trading Rules:
1. Seek Confluence: If momentum and sentiment are strongly aligned (both positive or both negative), take a directional position.
2. Preserve Capital: If momentum and sentiment contradict each other, or if both signals are very weak (close to 0), you must HOLD.

Provide your response strictly in the following format:
Decision: [BUY, SELL, or HOLD]
Reasoning: [Briefly explain if the signals show confluence or contradiction]
"""

    prompt_c = f"""You are an algorithmic macro-trader specializing in Bitcoin (BTC) market cycles.
You understand that BTC is heavily driven by institutional news flow and sustained momentum breakouts.

Market Data:
- BTC Price: {price}
- Daily Momentum: {momentum}
- FinBERT News Sentiment: {sentiment} (-1 to 1)

Instructions:
Evaluate the strength of the trend. Are we seeing a genuine momentum breakout backed by news sentiment, a breakdown, or just market noise?

Format your output exactly as follows:
Analysis: [One sentence evaluating the trend strength]
Decision: [BUY, SELL, or HOLD]
"""

    prompt_btc_few_shot = f"""You are a quantitative financial agent specializing in Bitcoin (BTC).
BTC is a momentum-driven asset. Your strategy is to ride the trend when mathematical momentum and news sentiment align, and to HOLD when signals conflict in order to preserve capital.

Here are examples of your logic:

[EXAMPLE 1: Bullish Confluence]
- Momentum: 0.04
- Daily News Sentiment Score: 0.8
Decision: BUY
Reasoning: Positive momentum perfectly aligns with strong positive sentiment, indicating a high-probability trend continuation.

[EXAMPLE 2: Bearish Confluence]
- Momentum: -0.05
- Daily News Sentiment Score: -0.7
Decision: SELL
Reasoning: Negative momentum is confirmed by highly negative news sentiment, signaling a high-probability sell-off.

[EXAMPLE 3: Conflicting Signals (Bullish News, Bearish Price)]
- Momentum: -0.03
- Daily News Sentiment Score: 0.6
Decision: HOLD
Reasoning: Positive news is being ignored by negative price action; conflicting signals dictate preserving capital.

[EXAMPLE 4: Weak/Neutral Signals]
- Momentum: 0.005
- Daily News Sentiment Score: 0.1
Decision: HOLD
Reasoning: Both momentum and sentiment are flat, providing no directional edge.

[CURRENT DATA]
- Current Price: {price}
- Momentum: {momentum}
- Daily News Sentiment Score: {sentiment}

Based on this, make a trading decision for tomorrow.
Provide your response strictly in the following format:
Decision: [BUY, SELL, or HOLD]
Reasoning: [One brief sentence explaining why]
"""

    prompt_btc_macro_few_shot = f"""You are a strict quantitative financial agent specializing in Bitcoin (BTC).
Your primary directive is capital preservation (maximizing Sharpe Ratio). You only take positions when the Macro Trend (5-Day), Daily Momentum, and News Sentiment are in perfect confluence. If they contradict, you MUST hold.

Here is your evaluation framework:

[EXAMPLE 1: Perfect Bullish Confluence]
- 5-Day Trend: +4.2%
- Daily Momentum: 0.03
- News Sentiment: 0.7
Reasoning: Trend is UP, Momentum is UP, Sentiment is POSITIVE. Full confluence achieved.
Decision: BUY

[EXAMPLE 2: Perfect Bearish Confluence]
- 5-Day Trend: -3.5%
- Daily Momentum: -0.04
- News Sentiment: -0.6
Reasoning: Trend is DOWN, Momentum is DOWN, Sentiment is NEGATIVE. Full confluence achieved.
Decision: SELL

[EXAMPLE 3: Trend Contradiction (Bull Trap)]
- 5-Day Trend: -5.1%
- Daily Momentum: 0.02
- News Sentiment: 0.5
Reasoning: Trend is DOWN, but Momentum and Sentiment are POSITIVE. Signals contradict. Risk of bull trap.
Decision: HOLD

[EXAMPLE 4: Weak/Mixed Signals]
- 5-Day Trend: +0.5%
- Daily Momentum: -0.01
- News Sentiment: 0.2
Reasoning: Trend is FLAT, Momentum is NEGATIVE, Sentiment is POSITIVE. No clear directional edge.
Decision: HOLD

[CURRENT DATA]
- 5-Day Trend: {trend_5d:.2%}
- Daily Momentum: {momentum}
- News Sentiment: {sentiment}

Provide your response strictly in the following format:
Reasoning: [State the alignment of Trend, Momentum, and Sentiment]
Decision: [BUY, SELL, or HOLD]
"""

    prompt_btc_macro_few_shot_price = f"""You are a quantitative financial agent specializing in Bitcoin (BTC).
Your primary directive is maximizing Sharpe Ratio. You evaluate Macro Trend (5-Day), Daily Price levels, Momentum, and News Sentiment.

[EXAMPLE 1: Strong Bullish]
- 5-Day Trend: +4.2%
- Daily Momentum: 0.03
- News Sentiment: 0.7
Reasoning: Price is holding high levels, Trend and Momentum are UP, supported by POSITIVE sentiment.
Decision: BUY

[EXAMPLE 2: Strong Bearish]
- 5-Day Trend: -3.5%
- Daily Momentum: -0.04
- News Sentiment: -0.6
Reasoning: Price is breaking down, Trend and Momentum are DOWN, confirmed by NEGATIVE sentiment.
Decision: SELL

[EXAMPLE 3: Mixed/Contradictory Signals]
- 5-Day Trend: -2.1%
- Daily Momentum: 0.02
- News Sentiment: 0.5
Reasoning: Short-term momentum is positive but fights the negative 5-day trend. Signals contradict.
Decision: HOLD

[CURRENT DATA]
- Current Price: ${price}
- 5-Day Trend: {trend_5d:.2%}
- Daily Momentum: {momentum}
- News Sentiment: {sentiment}

Provide your response strictly in the following format:
Reasoning: [Briefly state the alignment of Price, Trend, Momentum, and Sentiment]
Decision: [BUY, SELL, or HOLD]
"""

    # Format for the chat model
    messages = [{"role": "user", "content": prompt_btc_few_shot}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

    # Generate output
    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=150,
        temperature=0.1, # Low temperature for more deterministic/consistent output
        do_sample=True
    )
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    # 4. Parse the output using Regex
    decision_match = re.search(r'Decision:\s*(BUY|SELL|HOLD)', response, re.IGNORECASE)
    reasoning_match = re.search(r'Reasoning:\s*(.*)', response, re.IGNORECASE)

    decision_text = decision_match.group(1).upper() if decision_match else "NO DECISION"
    reasoning_text = reasoning_match.group(1).strip() if reasoning_match else "Could not parse reasoning."

    return pd.Series([decision_text, reasoning_text])

def get_smarter_decision(row):
    asset_name = row['asset']
    price = row['prices']
    momentum = row['momentum']
    trend_5d = row['trend_5d']
    sentiment = row['news_sentiment']
    sentiment_3d = row['sentiment_3d_avg']

    # UPGRADE: Few-Shot Prompting with a Profit-Seeking Persona
    prompt = f"""You are an objective quantitative trading algorithm designed to maximize Cumulative Return.
You actively identify trading opportunities based on momentum, trend, and sentiment. You take calculated positions.

Here are examples of how you should think:

[EXAMPLE 1]
- 5-Day Trend: 4.20%
- Daily Momentum: 0.05
- Today's News Sentiment: 1.0
- 3-Day Average Sentiment: 0.6
Decision: BUY
Reasoning: Strong upward momentum and sustained positive sentiment indicate a continuation of the rally.

[EXAMPLE 2]
- 5-Day Trend: -2.10%
- Daily Momentum: -0.03
- Today's News Sentiment: -1.0
- 3-Day Average Sentiment: -0.7
Decision: SELL
Reasoning: Deteriorating price trend combined with persistent negative news flow signals further downside.

[EXAMPLE 3]
- 5-Day Trend: 0.50%
- Daily Momentum: 0.01
- Today's News Sentiment: 0.0
- 3-Day Average Sentiment: 0.0
Decision: HOLD
Reasoning: Flat trend and neutral, conflicting sentiment provide no clear directional edge.

[CURRENT DATA FOR {asset_name}]
- 5-Day Trend: {trend_5d:.2%}
- Daily Momentum: {momentum}
- Today's News Sentiment: {sentiment}
- 3-Day Average Sentiment: {sentiment_3d:.2f}

Based on the current data, make a trading decision for tomorrow.
Provide your response strictly in the following format:
Decision: [BUY, SELL, or HOLD]
Reasoning: [One brief sentence explaining why]
"""

    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

    # Slightly increased temperature to allow the model to break out of repetitive loops
    generated_ids = model.generate(
        **model_inputs, max_new_tokens=50, temperature=0.1, do_sample=True
    )
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    # Extract decision and reasoning
    decision_match = re.search(r'Decision:\s*(BUY|SELL|HOLD)', response, re.IGNORECASE)
    reasoning_match = re.search(r'Reasoning:\s*(.*)', response, re.IGNORECASE)

    decision_text = decision_match.group(1).upper() if decision_match else "HOLD"
    reasoning_text = reasoning_match.group(1).strip() if reasoning_match else "Parse error."

    return pd.Series([decision_text, reasoning_text])

def get_dynamic_decision(row):
    asset_name = row['asset']
    price = row['prices']
    momentum = row['momentum']
    trend_5d = row['trend_5d']
    sentiment = row['news_sentiment']
    sentiment_3d = row['sentiment_3d_avg']

    # ---------------------------------------------------------
    # 1. THE TSLA CONTRARIAN PROMPT
    # ---------------------------------------------------------

    prompt = f"""You are an algorithmic trader specializing in {asset_name}.
TSLA is highly volatile, driven by retail hype, and often subject to "buy the rumor, sell the news" events.
You look for mean reversion and contrarian setups. You sell into extreme euphoria and buy extreme unjustified dips.

Examples of your logic:

[EXAMPLE 1: Contrarian Buy]
- 5-Day Trend: -6.50%
- Daily Momentum: -0.04
- Today's News Sentiment: -0.1
- 3-Day Average Sentiment: -0.3
Decision: BUY
Reasoning: The asset is deeply oversold on only mildly negative news, signaling a high probability of a mean-reversion bounce.

[EXAMPLE 2: Selling the Hype]
- 5-Day Trend: 8.20%
- Daily Momentum: 0.06
- Today's News Sentiment: 0.9
- 3-Day Average Sentiment: 0.8
Decision: SELL
Reasoning: Price has surged alongside euphoric sentiment, indicating a crowded trade and high risk of a pullback.

[EXAMPLE 3: Waiting out the chop]
- 5-Day Trend: -1.00%
- Daily Momentum: 0.01
- Today's News Sentiment: 0.2
- 3-Day Average Sentiment: 0.0
Decision: HOLD
Reasoning: Price action is flat and sentiment is mixed; there is no clear extreme to fade.

[CURRENT DATA FOR {asset_name}]
- 5-Day Trend: {trend_5d:.2%}
- Daily Momentum: {momentum}
- Today's News Sentiment: {sentiment}
- 3-Day Average Sentiment: {sentiment_3d:.2f}

Based on the current data, make a trading decision for tomorrow.
Provide your response strictly in the following format:
Decision: [BUY, SELL, or HOLD]
Reasoning: [One brief sentence explaining why]
"""


    prompt_tsla_divergence = f"""You are a contrarian quantitative trader specializing in Tesla (TSLA).
TSLA is driven by retail emotion, hype cycles, and short-squeezes. Your strategy is to identify extreme overextensions or divergences between price action and news sentiment to fade the crowd.

Evaluation Framework:

[EXAMPLE 1: Exhaustion / Divergence Buy]
- Current Price: $165.00
- 5-Day Trend: -8.50%
- Daily Momentum: -0.05
- Today's News Sentiment: -0.1
- 3-Day Average Sentiment: 0.2
Reasoning: Price has aggressively dumped (-8.5%), but recent sentiment is actually mildly positive, showing a divergence where sellers are exhausted.
Decision: BUY

[EXAMPLE 2: Euphoria / Selling the Hype]
- Current Price: $240.00
- 5-Day Trend: 12.20%
- Daily Momentum: 0.08
- Today's News Sentiment: 0.95
- 3-Day Average Sentiment: 0.85
Reasoning: Massive 5-day run-up combined with extreme euphoric sentiment indicates a crowded, overextended trade ripe for a sharp pullback.
Decision: SELL

[EXAMPLE 3: No Edge / Choppy]
- Current Price: $205.00
- 5-Day Trend: 1.20%
- Daily Momentum: 0.01
- Today's News Sentiment: 0.3
- 3-Day Average Sentiment: 0.2
Reasoning: Both price action and sentiment are mildly positive but lack the extremes or divergences required for a high-probability contrarian setup.
Decision: HOLD

[CURRENT DATA FOR {asset_name}]
- Current Price: ${price}
- 5-Day Trend: {trend_5d:.2%}
- Daily Momentum: {momentum}
- Today's News Sentiment: {sentiment}
- 3-Day Average Sentiment: {sentiment_3d:.2f}

Based on the current data, evaluate the setup.
Provide your response strictly in the following format:
Reasoning: [Analyze if there is extreme overextension or a divergence between price and sentiment]
Decision: [BUY, SELL, or HOLD]
"""

    messages = [{"role": "user", "content": prompt_tsla_divergence}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

    generated_ids = model.generate(
        **model_inputs, max_new_tokens=150, temperature=0.2, do_sample=True
    )
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

    # Extract decision and reasoning
    decision_match = re.search(r'Decision:\s*(BUY|SELL|HOLD)', response, re.IGNORECASE)
    reasoning_match = re.search(r'Reasoning:\s*(.*)', response, re.IGNORECASE)

    decision_text = decision_match.group(1).upper() if decision_match else "HOLD"
    reasoning_text = reasoning_match.group(1).strip() if reasoning_match else "Parse error."

    return pd.Series([decision_text, reasoning_text])

print("Running LLM Few-Shot Predictions...")
df_test = df_btc.copy()

# Apply the prompt function
df_test[['raw_decision' , 'reasoning']] = df_test.apply(get_decision_and_reasoning, axis=1)

# # 5. Map Decisions to Numerical Values
decision_map = {'BUY': 1, 'SELL': -1, 'HOLD': 0}
df_test['action'] = df_test['raw_decision'].map(decision_map).fillna(0)

# Map decisions as before
# decision_map = {'BUY': 1, 'SELL': -1, 'HOLD': 0}
# df_test['action'] = df_test['raw_decision'].map(decision_map).fillna(0)

# UPGRADE 3: The Confidence Filter
# Only trade if the LLM is highly confident (e.g., >= 8). Otherwise, force a HOLD (0).
# df_test['action'] = df_test.apply(
#     lambda x: x['raw_action'] if x['confidence'] >= 8 else 0,
#     axis=1
# )

# 6. Calculate Financial Metrics
# First, calculate the daily return of the asset.
# If we make a decision today, our return relies on the price change of the *next* day.
df_test['daily_return_asset'] = df_test['prices'].pct_change().shift(-1)

# Calculate strategy returns: returns_i = daily_i * action_i
df_test['strategy_return'] = df_test['daily_return_asset'] * df_test['action']

# Drop the last row since its future return is NaN
df_valid = df_test.dropna(subset=['strategy_return']).copy()

# Calculate Cumulative Return (CR)
# Formula: Product of (1 + return) - 1
cumulative_return = (1 + df_valid['strategy_return']).prod() - 1

# Calculate Sharpe Ratio (SR)
# Formula: (Mean / Std) * sqrt(252 trading days)
mean_return = df_valid['strategy_return'].mean()
std_return = df_valid['strategy_return'].std()

if std_return > 0:
    sharpe_ratio = (mean_return / std_return) * np.sqrt(252)
else:
    sharpe_ratio = 0.0

print("\n--- Trading Decisions Output ---")
print(df_valid[['date', 'prices', 'raw_decision', 'action', 'reasoning', 'strategy_return']].head(10))

print("\n--- Performance Metrics ---")
print(f"Cumulative Return (CR): {cumulative_return:.4%}")
print(f"Sharpe Ratio (SR): {sharpe_ratio:.4f}")

"""Tesla"""

print("Running LLM Few-Shot Predictions...")
df_test_tsla = df_tsla.copy()

# # Apply the prompt function
df_test_tsla[['raw_decision', 'reasoning']] = df_test_tsla.apply(get_dynamic_decision, axis=1)
# df_test_tsla[['raw_decision', 'reasoning']] = df_test_tsla.apply(get_decision_and_reasoning, axis=1)

# # 5. Map Decisions to Numerical Values
# decision_map = {'BUY': 1, 'SELL': -1, 'HOLD': 0.5, 'NO DECISION': 0}
# df_test_tsla['action'] = df_test_tsla['raw_decision'].map(decision_map).fillna(0)

# Map decisions as before
decision_map = {'BUY': 1, 'SELL': -1, 'HOLD': 0}
df_test_tsla['action'] = df_test_tsla['raw_decision'].map(decision_map).fillna(0)

# UPGRADE 3: The Confidence Filter
# Only trade if the LLM is highly confident (e.g., >= 8). Otherwise, force a HOLD (0).
# df_test_tsla['action'] = df_test_tsla.apply(
#     lambda x: x['raw_action'] if x['confidence'] >= 8 else 0,
#     axis=1
# )

# ... Then calculate Strategy Return, CR, and SR exactly as before!

# 6. Calculate Financial Metrics
# First, calculate the daily return of the asset.
# If we make a decision today, our return relies on the price change of the *next* day.
df_test_tsla['daily_return_asset'] = df_test_tsla['prices'].pct_change().shift(-1)

# Calculate strategy returns: returns_i = daily_i * action_i
df_test_tsla['strategy_return'] = df_test_tsla['daily_return_asset'] * df_test_tsla['action']

# Drop the last row since its future return is NaN
df_valid = df_test_tsla.dropna(subset=['strategy_return']).copy()

# Calculate Cumulative Return (CR)
# Formula: Product of (1 + return) - 1
cumulative_return = (1 + df_valid['strategy_return']).prod() - 1

# Calculate Sharpe Ratio (SR)
# Formula: (Mean / Std) * sqrt(252 trading days)
mean_return = df_valid['strategy_return'].mean()
std_return = df_valid['strategy_return'].std()

if std_return > 0:
    sharpe_ratio = (mean_return / std_return) * np.sqrt(252)
else:
    sharpe_ratio = 0.0

print("\n--- Trading Decisions Output ---")
print(df_valid[['date', 'prices', 'raw_decision', 'action', 'reasoning', 'strategy_return']].head(10))

print("\n--- Performance Metrics ---")
print(f"Cumulative Return (CR): {cumulative_return:.4%}")
print(f"Sharpe Ratio (SR): {sharpe_ratio:.4f}")

